version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8u242-jdk
    steps:
      - checkout
      - run:
          name: Determine which directories have changed
          command: |
            git diff --no-commit-id --name-only -r `git log -n 2 --oneline --pretty=format:"%h" | tail -n1` | cut -d/ -f1 | sort -u >  projects
            printf "Modified directories:\n"
            cat projects
            while read project; do
              if grep -Fxq $project project-dirs; then
                printf "\nTriggerring build for project: "$project
                curl -s -u ${CIRCLE_TOKEN}: -d build_parameters[CIRCLE_JOB]=${project} https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH
              fi
            done < projects
  cargo-start:
    docker:
      - image: circleci/openjdk:8u242-jdk
    working_directory: ~/ddd-cargo-maven-module-example
    steps:
      - install-jar
      - build-service

commands:
  install-jar:
    description: maven install jar files
    steps:
    - checkout:
        path: ~/ddd-cargo-maven-module-example
    - run: mvn install package
  build-service:
    description: "Build a service and push image to dockerhub"
    steps:
      # git pull
      - checkout:
          path: ~/ddd-cargo-maven-module-example

      - setup_remote_docker

      - run:
          name: Login to Dockerhub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run:
          name: build and push image
          command: |
            cd cargo-start
            ls .
            mvn dockerfile:build dockerfile:push -Ddocker.image.tag=Build-${CIRCLE_BUILD_NUM}-CI -Ddockerfile.maven.settings.auth=false