version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8u242-jdk
    steps:
      - checkout
      - run:
          name: Determine which directories have changed
          command: |
            curl -s -u ${CIRCLE_TOKEN}: -d build_parameters[CIRCLE_JOB]=cargo-start https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH
  cargo-start:
    docker:
      - image: circleci/openjdk:8u242-jdk
    working_directory: ~/ddd-cargo-maven-module-example
    steps:
      - install-jar:
          service-name: "cargo-start"
      - build-service:
          service-name: "cargo-start"

commands:
  install-jar:
    description: maven install jar files
    parameters:
      service-name:
        type: string
    steps:
    - checkout:
        path: ~/ddd-cargo-maven-module-example
    - run: mvn install package
  build-service:
    description: "Build a service and push image to dockerhub"
    parameters:
      service-name:
        type: string
    steps:
      # git pull
      - checkout:
          path: ~/ddd-cargo-maven-module-example

      - setup_remote_docker

      - run:
          name: Login to Dockerhub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run:
          name: build and push image
          command: |
            cd cargo-start
            ls .
            mvn dockerfile:build dockerfile:push -Ddocker.image.tag=Build-${CIRCLE_BUILD_NUM}-CI -Ddockerfile.maven.settings.auth=false